### Phones Create

POST http://localhost:3001/api/phones
Content-Type: application/json

{
  "name": "Huawei P50 Pro",
  "processor": "Kirin 9000",
  "camera": "50 MP",
  "battery": "Li-Po 4360 mAh",
  "price": 3200,
  "img": "https://fdn2.gsmarena.com/vv/bigpic/huawei-p50-pro.jpg"
}

### Phones Update

PUT http://localhost:3001/api/phones
Content-Type: application/json

{
  "name": "",
  "processor": "",
  "camera": "",
  "battery": "",
  "price": ,
  "img": ""
}

### Phones Delete

DELETE http://localhost:3001/api/phones/6287f7ad0bf6011924919f4f

### Users Create

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "gogagoga",
  "name": "goga",
  "password": "goga12345"
}

### Users Update

PUT http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "",
  "name": "",
  "password": "",
  "admin": 
}

### Users Delete

DELETE http://localhost:3001/api/users/62880000792e5efc1681b781

### Login

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "",
  "password": ""
}