### Phones Create

POST http://localhost:3001/api/phones
Content-Type: application/json

{
  "name": "",
  "processor": "",
  "camera": "50 MP",
  "battery": "",
  "price": ,
  "img": ""
}

### Phones Update

PUT http://localhost:3001/api/phones
Content-Type: application/json

{
  "name": "",
  "processor": "",
  "camera": "",
  "battery": "",
  "price": ,
  "img": ""
}

### Phones Delete

DELETE http://localhost:3001/api/phones/

### Users Create

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "",
  "name": "",
  "password": ""
}

### Users Update

PUT http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "",
  "name": "",
  "password": "",
  "admin": 
}

### Users Delete

DELETE http://localhost:3001/api/users/

### Login

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "",
  "password": ""
}